### ISSUE TITLE
Segmentation fault when __html__ method raises an exception

### ISSUE THREAD

**Issue by mthuurne** [pallets/markupsafe#108]
The following code fragment causes a segmentation fault if the `_speedups.c` version of `escape()` is used:
```py
from markupsafe import escape

class Test(object):
    def __html__(self):
        raise ValueError(123)

escape(Test())
```

I think the likely cause is that `PyObject_CallObject(html, NULL)` returns `NULL` on an exception, but the returned value is not checked for `NULL` before it is passed to `PyObject_CallFunctionObjArgs()` and `Py_DECREF()`:

```c
	/* if the object has an __html__ method that performs the escaping */
	html = PyObject_GetAttr(text ,id_html);
	if (html) {
		s = PyObject_CallObject(html, NULL);
		Py_DECREF(html);
		/* Convert to Markup object */
		rv = PyObject_CallFunctionObjArgs(markup, (PyObject*)s, NULL);
		Py_DECREF(s);
		return rv;
	}
```

**Comment by mickeyl** [comment]
Removing the extension module helps as a workaround, since in that case the python-fallback is used.

**Comment by samuelcolvin** [comment]
Hi is there a timeline for fixing this?

We're getting this problem in production so a fix would be wonderful.

**Comment by davidism** [comment]
I'd be happy to review a PR to move this along faster. I'm currently focused on Werkzeug, and this bug hasn't seemed to affect me, so it's not currently my priority.

I may be misunderstanding, but it doesn't seem like `__html__` should be raising an exception, you may want to address that regardless of a fix for this.

**Comment by samuelcolvin** [comment]
Yup, we're in django and were raising `SuspiciousOperation` inside a form render which was causing the problems.

I'm afraid my c is aweful. Would probably be much faster for you to fix it, but maybe I'll try when I have some free time.

**Comment by mthuurne** [comment]
I opened a pull request (#109) that should fix this bug, including a test case.

I wasn't sure whether to restrict execution to run only with the native implementation: the bug is specific to the native code, but the test itself can run just fine without the native code, so in the end I decided to not restrict it. But if you disagree, feel free to change it.
