### ISSUE TITLE
Wheel support for aarch64

### ISSUE THREAD

**Issue by odidev** [pallets/markupsafe#134]
**Summary**
Installing markupsafe on aarch64 via pip using command "pip3 install pyyaml" tries to build wheel from source code

**Problem description**
Markupsafe don't have wheel for aarch64 on PyPI repository. So, while installing markupsafe via pip on aarch64, pip builds wheel for same resulting in it takes more time to install markupsafe. Making wheel available for aarch64 will benefit aarch64 users by minimizing markupsafe installation time.

**Expected Output**
Pip should be able to download markupsafe wheel from PyPI repository rather than building it from source code.

@markupsafe-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make markupsafe wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by davidism** [comment]
You'll want to work with the cibuildwheel project, we use them to build wheels.

**Comment by davidism** [comment]
Linux aarch64 was added in #173.
