### ISSUE TITLE
Consider using the stable API when building wheels for CPython

### ISSUE THREAD

**Issue by mattip** [pallets/markupsafe#175]
I noticed your tweet about having lots of wheels (thanks for the PyPy one BTW). Perhaps you could consider creating stable ABI wheels? I think if you add
```
[bdist_wheel]
py-limited-api = cp34
```
to the `setup.cfg` then `python setup.py bdist_wheel` will build something like `MarkupSafe-1.1.1-cp34-abi3-macosx_10_6_intel.whl` which any `cpython>-3.4` will support on macosx. This would save having to create a cpython-3.4, cpython3.5, ... wheels and would also mean you would future proof yourself for any new versions of cpython.

You might need to adjust the CI wheel build to only build the wheel once, since the various versions of CPython will build a wheel with the same name, I think `bdist_wheel` is unhappy if a wheel already exists.

**Comment by davidism** [comment]
We only support 3.6+, I'm assuming I could use `cp36` there? Unfortunately, I still know very little about platform wheels, it's why I rely on cibuildwheel to do everything for me. @joerick, does cibuildwheel support this?

**Comment by joerick** [comment]
We don't support it directly, there's an open issue joerick/cibuildwheel#78, but you could set `py-limited-api` in setup.cfg, and then `CIBW_BUILD=cp36-*`, and you'd get one wheel that supports everything CPython 3.6+.

I'm actually not sure how PyPy would factor into this - @mattip, does PyPy support limited-api, or would you still need platform-specific wheels there?

**Comment by mattip** [comment]
> We only support 3.6+, I'm assuming I could use cp36 there? 

Yes. You might want to adjust your setup.cfg to mention cp36+, on [PyPI](https://pypi.org/project/MarkupSafe/1.1.1/#files) there are wheels for 3.4, 3.5 and the identifier on the left also has those versions.

> does PyPy support limited-api, or would you still need platform-specific wheels there?

Sorry, not yet. We have not really discussed how to do this. So it still needs a pypy-wheel per python version.

**Comment by joerick** [comment]
> > does PyPy support limited-api, or would you still need platform-specific wheels there?
> 
> Sorry, not yet. We have not really discussed how to do this. So it still needs a pypy-wheel per python version.

Makes sense. So then I think `py-limited-api = cp36` in setup.cfg and `CIBW_BUILD=cp36-* pp*` would work... though I can't make any promises! Hopefully we'll have some official support some day :)

**Comment by davidism** [comment]
Thanks, I just subscribed to that issue. I'll try out those settings, I guess I would test it by trying to install the wheel on other Pythons? I'm still not 100% confident because I only have access to Linux x64 and Windows for testing.

**Comment by henryiii** [comment]
Yes, I'd do it one of two ways for now: for GHA, upload-artifact the built wheel, then make a matrix job that depends on the previous job, downloads the wheel with download-artifact, then runs setup-python and then runs the tests. Very similar to how you might release, see https://scikit-hep.org/developer/gha_wheels#publishing, but test instead of publish. Or if you like repeating yourself, make a chain of setup-pythons followed by installing and running the tests.

The other way, and generic for other platforms, would be to use nox. You'd setup-python (GHA, or however your other platform handles it) for all the versions you are interested in, one after the other, then you'd have a `noxfile.py` something like this:

```python
import nox

@nox.session(python=["3.6", "3.7", "3.8", "3.9"])
def test_wheel(session):
    session.install("pytest")
    session.install("./wheelhouse/*.whl") # Might need to manually expand
    session.run("pytest")
```

Eventually cibuildwheel might use the "other" selected python platforms to just test the wheel produced on the earliest one, but this should work today.

**Comment by davidism** [comment]
I just tried building a cp36-abi3 wheel, then installed it on Python 3.7, and I was not able to import the speedups. Examining the wheel, the speedups were still named `_speedups.cpython-36m-x86_64-linux-gnu.so`, so I'm not sure how Python 3.7 would know it can use that.

**Comment by mattip** [comment]
did you clean out any possible previous build?

**Comment by davidism** [comment]
I tried cloning a new copy of the repo, same result.

**Comment by davidism** [comment]
Also just tried removing some of the custom stuff in `setup.py` (which doesn't seem particularly necessary now anyway), since I thought that might be affecting it, but same result.

**Comment by davidism** [comment]
31dcd439a3cb0ab75ae8cdb7408f8c05f1f45c1c on the new-cibuildwheel-features branch for the changes.

**Comment by henryiii** [comment]
The new features are only providing better support for the limited api in a matrix; cibuildwheel shouldn't be controlling the name before or after the changes (I think). It's definitely not going to fix something you can't do by hand.

Are you use you might not have used `py-limited-api` instead of `py_limited_api`? I'm also not completely sure that setting is available in setup.cfg, I've always seen it in setup.py, like [for libsass](https://github.com/sass/libsass-python/blob/master/setup.py).

**Comment by henryiii** [comment]
Ahh, nevermind, `py_limited_abi` needs to be set on the Extension - it isn't a setup() arg. So it has to be in the setup.py.

**Comment by mattip** [comment]
Ahh, right. I was patterning myself after [this setup.cfg](https://github.com/Quansight/pnumpy/blob/main/setup.cfg#L62) but forgot about [this line in the setup.py](https://github.com/Quansight/pnumpy/blob/main/setup.py#L177)

**Comment by davidism** [comment]
Thanks, that explains why the name isn't fixed. :-) Wish there was more documentation about this, I couldn't find anything in setuptools or wheel.

Just tried the extra line, I can build the cp36-abi tag then install and import it in 3.7.

**Comment by davidism** [comment]
I tried building on Windows, and ran into another issue. If I build on 3.6, and then try to install and `from mkarupsaef import _speedups` on 3.9, I get `ImportError: DLL load failed while importing _speedups: The specified module could not be found.`

Also, I get the `cp36-abi3` tag even if I build on another version like cp39. Additionally on Windows, the compiled file is just called `_speedups.pyd` instead of `_speedups.abi3.pyd`.

**Comment by henryiii** [comment]
You can build an limited API build from any version of Python supported. 3.9 builds exactly the same wheel as 3.6, it's based on the minimum you set, not the current version of Python.

The windows behavior sounds a bit like a bug...

**Comment by davidism** [comment]
Opened #186 with the changes so far. Once the build workflow completes, we can download the artifact zip of all the wheels.

**Comment by davidism** [comment]
Looks like the Windows behavior is a bug, I went back to Linux and tried the same thing and it worked there.

**Comment by mattip** [comment]
On windows the c-extension module is supposed to have a runtime dependency on `python3.dll` rather than `python36.dll` (or `python39.dll`). The DLL should be in the same directory as python.exe. If it is missing, loading the c-extension will fail with that cryptic message.

**Comment by davidism** [comment]
I installed from https://www.python.org/downloads/, if they're not configured correctly for abi3 wheels, this is likely to cause problems for most users.

**Comment by davidism** [comment]
Oh wait, I forgot that there were still Windows issues...

**Comment by davidism** [comment]
There's a `python3.dll` in every python version I have installed, so I don't know what the issue is. Is there a way to debug this more? Or is there something different that the C code needs to do? Maybe I should just ping @zooba the Windows expert? :-)

**Comment by davidism** [comment]
I thought it might be my dev setup at first, but the builds from CI have the same issue. So either there's something wrong in our code or build, or it's a bug in distutils/setuptools/wheel/pip.

**Comment by henryiii** [comment]
Have you tried building locally? Maybe there's a chance that the python3.dll is missing from the NuGet packages cibuildwheel uses? (Though that would be really weird)

**Comment by davidism** [comment]
Yeah, I noticed this building locally first.

**Comment by davidism** [comment]
So we were missing one more thing to enable the limited API, need to add `define_macros=[("Py_LIMITED_API", None)]` to the `Extension`. Once I did that, got a ton of errors that basically none of the Unicode API we use is available. I know nothing about the C API or Unicode, it was all written by other people, so I'm probably going to have to go back to building a ton of wheels unless someone with more C knowledge can devote their time to this.

**Comment by davidism** [comment]
Also not sure if that define was what was causing the Windows issue too, can't determine that until the extension actually builds again.

**Comment by davidism** [comment]
I'll continue to build version wheels for now. While it would be nice to build fewer wheels with abi3, it's not particularly a problem for me to push a new CI config then upload the new wheels when a new Python version is available.
