### ISSUE TITLE
Were Python packages updated by markupsafe?

### ISSUE THREAD

**Issue by rlvrs** [pallets/markupsafe#182]
Hi.

I am writing this as I couldn't find where would you publicly announce this.
We have a build that depends on markupsafe and we use pipenv to manage dependencies. 

However, since the 1st of Feb we are unable to build as the hashes of the packages have changed.
I realised that you have updated versions [here](https://pypi.org/project/MarkupSafe/#files) on the 29th Jan 2021. However, I want to double-check that this was really updated by markupsafe contributors.

I was expecting to see some sort of announcement/release notes or anything of the sort.
Perhaps it exists and I could not find it...

This might not be really an issue here, but I don't know the best place to put this question on.

Thank you in advance

**Comment by davidism** [comment]
We added more wheels, but did not change the existing wheels. Perhaps your install tool downloaded a more appropriate wheel. You'll want to check what wheel is downloaded and use the appropriate hash from PyPI.
