### ISSUE TITLE
Package missing on files.pythonhosted.org

### ISSUE THREAD

**Issue by ksdme** [pallets/markupsafe#222]
I just noticed that our builds failed because of a 404 on https://files.pythonhosted.org/packages/source/m/MarkupSafe/MarkupSafe-2.0.1.tar.gz and every other package dependency we have seems to work fine. Maybe something you want to look into.

**Comment by davidism** [comment]
I can't reproduce this issue. `pip install --no-binary markupsafe markupsafe` installs `MarkupSafe-2.0.1.tar.gz` successfully. I have no control over how PyPI serves files. That link does not appear to match the links on the PyPI project page, I suggest you examine why your build is using it.

**Comment by ksdme** [comment]
Thanks for the checking. We ended up using the nix mirror and it seems to work fine that way.

**Comment by davidism** [comment]
I don't know what the nix mirror is. Note that the only officially supported builds are on PyPI, be sure you understand what you're getting when picking a third-party source.
