### ISSUE TITLE
Trying to install MarkupSafe 2.0.1 or 2.0.0 using pip resulted in "installing" 0.0.0 instead

### ISSUE THREAD

**Issue by lydia-duncan** [pallets/markupsafe#228]
I'm trying to install the latest version of this package for my testing.  I encountered a weird error when trying to install it with a setup that I later realized was incompatible - having a better error message would have helped me determine the problem sooner.

Basically, when trying to install the latest version of MarkupSafe with Python 3.5, instead of giving me an "incompatible version error" or something along those lines, pip installed a 0.0.0 package which fulfilled conditions in other parts of my build but was basically useless and hid the problem from me for a bit.

Here's the output when I tried to go from 2.0.1 to 2.0.0 to see if that worked instead (before I realized that my Python version was at fault)
```
$ python3 -m pip install MarkupSafe==2.0.0
Collecting MarkupSafe==2.0.0
  Downloading https://files.pythonhosted.org/packages/67/6a/5b3ed5c122e20c33d2562df06faf895a6b91b0a6b96a4626440ffe1d5c8e/MarkupSafe-2.0.0.tar.gz
  Requested MarkupSafe==2.0.0 from https://files.pythonhosted.org/packages/67/6a/5b3ed5c122e20c33d2562df06faf895a6b91b0a6b96a4626440ffe1d5c8e/MarkupSafe-2.0.0.tar.gz#sha256=4fae0677f712ee090721d8b17f412f1cbceefbf0dc180fe91bab3232f38b4527, but installing version 0.0.0
Building wheels for collected packages: MarkupSafe
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /<elided for privacy>/.cache/pip/wheels/7d/e1/0b/0d6045c0f0280f2c7477da1f96f497b02041a7ff74e29e285b
Successfully built MarkupSafe
Installing collected packages: MarkupSafe
  Found existing installation: MarkupSafe 0.0.0
    Uninstalling MarkupSafe-0.0.0:
      Successfully uninstalled MarkupSafe-0.0.0
Successfully installed MarkupSafe-0.0.0
You are using pip version 8.1.1, however version 21.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Environment:

- Python version: 3.5
- MarkupSafe version: 2.0.1, and 2.0.0

If it helps, I was working on an Ubuntu 32 bit system.  But I suspect the problem is just generally applicable to Python 3.5 and lower

**Comment by ThiefMaster** [comment]
> You are using pip version 8.1.1, however version 21.1.2 is available.

There's the problem. You're using a 5-year-old version of `pip`. Use a virtualenv and update pip/setuptools in there. Also, we no longer support anything lower than Python 3.6.

**Comment by lydia-duncan** [comment]
For reference, I did try to update my pip in a virtual environment and the latest version of pip was incompatible with Python 3.5.  Or at least, I assume that's why it didn't like the formatting when trying to install anything

**Comment by ThiefMaster** [comment]
ah, i guess the problem is that your pip is so old, that when you try to update it, it updates itself to a version that's too new...
