### ISSUE TITLE
Python 3.10 manylinux wheels

### ISSUE THREAD

**Issue by hrnciar** [pallets/markupsafe#237]
Hello.

Could you please release CPython 3.10 manylinux wheels on PyPI? 

Python 3.10.0 release candidate 1 was released this week: https://www.python.org/downloads/release/python-3100rc1/

It should be quite safe to release wheels for release candidate. ABI for Python 3.10 should be frozen from now on, even for bugfixes. From release notes: 

> There will be no ABI changes from this point forward in the 3.10 series and the goal is that there will be as few code changes as possible.

Thank You.

**Comment by davidism** [comment]
This is already on my todo list.

**Comment by davidism** [comment]
All builds produced by cibuildwheel 2.1.1, including Python 3.10, manylinux_2_5, manylinux_2_17, and Python 3.8 universal2, are now available for MarkupSafe 2.0.1 on PyPI.
