### ISSUE TITLE
Installing MarkupSafe-2.0.1 on macOS 11.5

### ISSUE THREAD

**Issue by MarioKlebsch** [pallets/markupsafe#241]
I am trying to install MarkupSafe-2.0.1 on macOS 11.5, but I get an error during installation. Here is what I am trying;

```
$ PREFIX=$HOME/tmp/MarkupSafe
$ PYTHONPATH=$PREFIX/lib/python2.7/site-packages/
$ export PYTHONPATH
$ mkdir -p $PYTHONPATH
$ python setup.py install --prefix $PREFIX
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    run_setup(True)
  File "setup.py", line 44, in run_setup
    ext_modules=ext_modules if with_binary else [],
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/distutils/core.py", line 124, in setup
    dist.parse_config_files()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/dist.py", line 698, in parse_config_files
    ignore_option_errors=ignore_option_errors)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/config.py", line 120, in parse_configuration
    meta.parse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/config.py", line 425, in parse
    section_parser_method(section_options)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/config.py", line 398, in parse_section
    self[name] = value
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/config.py", line 183, in __setitem__
    value = parser(value)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/config.py", line 513, in _parse_version
    version = self._parse_attr(value, self.package_dir)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/setuptools/config.py", line 349, in _parse_attr
    value = getattr(module, attr_name)
AttributeError: 'module' object has no attribute '__version__'
$
```

Environment:
- macOS 11.5
- Python version: Python 2.7.16
- MarkupSafe version: MarkupSafe-2.0.1

**Comment by ThiefMaster** [comment]
You are using Python 2.7 which is EOL and unsupported. You need to use markupsafe 1.x if you REALLY want to use Python 2.

**Comment by MarioKlebsch** [comment]
> You are using Python 2.7 which is EOL and unsupported. You need to use markupsafe 1.x if you REALLY want to use Python 2.

Shouldn't  setup.py check the python version and print a decent error message?

> Also, do not use setup.py install - use pip install instead (which would be able to tell you about this incompatibility or, when using PyPI, get a version that is supported in your environment)

I tried this first, but it did not work:
> odo:MarkupSafe-2.0.1 mario$ pip install
> -bash: pip: command not found
> odo:MarkupSafe-2.0.1 mario$ 

I stumbled across https://docs.python.org/2/install/index.html, which told me to run setup.py.

In fact, I do not really want to install MarkupSafe, I wanted to install SDRPlusPlus (https://github.com/AlexandreRouma/SDRPlusPlus) and am just trying to find my way through its jungle of dependencies. SDRPlusPlus needs libvolk, which needs Mako, which loads MarkupSafe during installation and fails.

macOS is listed as supported platform for SDRplusplus, so I tried my luck.

Many thanks you for the support, you supplied. Now I know, that I also have to build python3 first.

73, Mario

**Comment by davidism** [comment]
You're using both an unsupported version of Python and pip and setuptools. You need to upgrade all three.

> Shouldn't setup.py check the python version and print a decent error message?

No, you're installing a wheel, the whole point is that it doesn't execute code such as setup.py at install time. It's up to pip to choose a compatible version, but you have such an old pip that it doesn't know how.

**Comment by MarioKlebsch** [comment]
> > Shouldn't setup.py check the python version and print a decent error message?
>
> No, you're installing a wheel,

What the hell is a wheel?

I just downloaded a tar.gz-file, unpacked it and tried to build it, as it is a dependency of some other software, I want to build.

> the whole point is that it doesn't execute code such as setup.py at install time. 

When it does not execute code, why does it print out a call stack?

> It's up to pip to choose a compatible version, but you have such an old pip that it doesn't know how.

As I wrote earlier, I doesn't look like I have pip:
```
odo:MarkupSafe-2.0.1 mario$ pip install
-bash: pip: command not found
odo:MarkupSafe-2.0.1 mario$ 
```
pip wasn't on any list of dependencies, an no configure or CMakeLists.txt complained on not finding pip.

It doesn't seem to me that C/C++ programmers are lost in the world of python, even if they simply want to install a program written in python.

73, Mario

**Comment by ThiefMaster** [comment]
Are you sure it's not enough if you install mako using your distribution's package manager? That may be enough for you to build that other library that needs it... Or you could do what it suggests and install `libvolk2-dev ` using your distribution's package manager.
