### ISSUE TITLE
During Deployment of  Flask with mod_wsgi in CentOs

### ISSUE THREAD

**Issue by subhasish1315** [pallets/markupsafe#242]
Hi ,
When I am trying to deploy my sample flask application in CentOS with Apache mod_wsgi  I am getting the below error 
But when I am trying to run in development mode, it is working perfectly.

APP Directory Contains with virtual ENV: 
            | --  All files regarding ENV
            | --  app.py
            | --  SSHC2.wsgi

My app.py contains - 

```
from flask import Flask,render_template,escape,jsonify
from flask_cors import CORS

app = Flask(__name__)
CORS(app)

@app.route("/")
def root():
    #return render_template("home.html")
    return "Hello"
      
if __name__ == "__main__":
    app.run(host='0.0.0.0', port=5000, debug=True)
```

My SSHC2.wsgi contains

```
import sys
import site

site.addsitedir('/var/www/SSHC2/lib/python3.9/site-packages')

sys.path.insert(0, '/var/www/SSHC2')

from app import app as application
```

Added lines in /etc/httpd/conf/httpd.conf

```
Listen servername:5000
<VirtualHost servername:5000>

     ServerName APPNAME.com

     WSGIDaemonProcess SSHC2 user=apache group=apache threads=2

     WSGIScriptAlias / /var/www/SSHC2/SSHC2.wsgi
     
     <Directory /var/www/SSHC2>
         Require all granted
     </Directory>

</VirtualHost>
```

But after restarting the apache Server,  when I am trying to open servername:5000   I am getting a syntax error in the apache error log with markupsafe library. 

```
Traceback (most recent call last):
File "/var/www/SSHC2/wsgi.py", line 8, in <module>
from app import app as application
File "/var/www/SSHC2/app.py", line 3, in <module>
from flask import Flask,render_template
File "/var/www/SSHC2/lib/python3.9/site-packages/flask/__init__.py", line 1, in <module>
from markupsafe import escape
File "/var/www/SSHC2/lib/python3.9/site-packages/markupsafe/__init__.py", line 10
def __html__(self) -> str:
                   ^
SyntaxError: invalid syntax

```
Environment:

- Python version:  3.9
- MarkupSafe version: 2.0.0

Please let me know if this is  error is markupsafe library or error in my application deployment procedure.

**Comment by ThiefMaster** [comment]
You're running the code with Python 2 for some reason. Also, this is the wrong place; use Discord, IRC or GitHub Discussions for questions about your own code.
