### ISSUE TITLE
Whether to consider excluding source data files from distribution

### ISSUE THREAD

**Issue by tklltkioc** [pallets/markupsafe#272]
```shell
os:centos 7.9
python:3.7.4
platform:CPython

pip list:
pip        20.2.2
setuptools 40.4.3
wheel      0.35.1
```

Delete the following lines of code
https://github.com/pallets/markupsafe/blob/7abfc64c3117c139ff4e430c590187067e8f3115/setup.cfg#L35
```shell
[options]
packages = find:
package_dir = = src
include_package_data = true 
python_requires = >= 3.7
```
-->
```shell
[options]
packages = find:
package_dir = = src
python_requires = >= 3.7
```
we can get compiled files excluding source files，should it be done？
![image](https://user-images.githubusercontent.com/38203731/149293994-049e85ba-6971-48fc-b6b7-817c1fcb3dad.png)

![image](https://user-images.githubusercontent.com/38203731/149294125-80b69dff-3350-48fb-8021-e3cffb07c0d0.png)

**Comment by davidism** [comment]
I though `include_package_data` was needed in order to use `MANIFEST.in`. Apparently it isn't, but I don't know when that changed. I don't see much value in dropping the c file, since all the other source py files are there (by definition).
