### ISSUE TITLE
Breaking change in 2.1.0

### ISSUE THREAD

**Issue by yvsppt** [pallets/markupsafe#286]
After installing a tiers tool, this error occured:

File "C:\Users\yves.pipault\AppData\Roaming\Python\Python310\site-packages\jinja2\utils.py", line 642, in <module>
    from markupsafe import Markup, escape, soft_unicode

Environment:

- Python version: 3.10
- MarkupSafe version: 2.1.0

Workaround:
pip install markupsafe==2.0.1

According to changelog of version 2.1.0, we can read: 
> Remove soft_unicode, which was previously deprecated. Use soft_str instead. [#261](https://github.com/pallets/markupsafe/pull/261)

That is a BREAKING CHANGE so you SHOULD increase the MAJOR version according to semantic versionning: https://semver.org/

**Comment by MetRonnie** [comment]
> Your application has likely been printing a warning every single time you've used Jinja2 as well, about this deprecation. If not, you might want to look into how you can catch these DeprecationWarnings before they break you.

Jinja2 is under the same organisation as this repo!

**Comment by pradyunsg** [comment]
What's the point you're trying to make? You realise this only happens on unsupported versions of Jinja2 right?

https://github.com/pallets/jinja/issues/1585#issuecomment-1043892628

**Comment by davidism** [comment]
Please read https://hynek.me/articles/semver-will-not-save-you/, then use a tool like [pip-tools](https://pypi.org/project/pip-tools/) to pin your dependencies and control when you get updates. Additionally, be sure to run your tests with deprecation warnings treated as errors so that you get notified of these types of changes early.

**Comment by thetic** [comment]
> You are using an unsupported version of Jinja.

May I ask where this is communicated? I would like to stay up to date on supported versions.

**Comment by davidism** [comment]
The only supported version is the latest version (2.1.x), and the development version (main).

**Comment by thetic** [comment]
is this documented anywhere?

**Comment by pradyunsg** [comment]
It’s the implied contract for most OSS projects. See https://bernat.tech/posts/version-numbers, specifically [What’s the problem with semantic versioning?](https://bernat.tech/posts/version-numbers/#whats-the-problem-with-semantic-versioning) — If there’s no documented stability policy, the implied stability policy is what @davidism noted above: only the latest release is “supported”, to the extent support is even promised by an OSS project that you aren’t funding.

See the license, and specifically what the warranties it notes.
