### ISSUE TITLE
Cannot import markupsafe in Python 3.1 or 3.2 due to explicit unicode literals

### ISSUE THREAD

**Issue by lpsinger** [pallets/markupsafe#31]
I cannot import markupsafe in Python 3.1 or 3.2. This is because it uses explicit unicode literals in a few places, which were absent in Python 3.1 and 3.2 [but restored in Python 3.3](http://legacy.python.org/dev/peps/pep-0414/).

```
$ python3.2
Python 3.2.5 (default, Nov 18 2013, 15:24:38) 
[GCC 4.2.1 Compatible Apple LLVM 5.0 (clang-500.2.79)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import markupsafe
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.2/lib/python3.2/site-packages/markupsafe/__init__.py", line 70
    def __new__(cls, base=u'', encoding=None, errors='strict'):
                            ^
SyntaxError: invalid syntax
```

Could this be either fixed, or else the limitation to Python <= 2.7 or >= 3.3 documented in the README file and the PyPI classifiers?

**Comment by hbsdev** [comment]
If someone needs to get arouond this:

1) go to the site-packages folder and remove the two markupsafe folders in there

2) Install version 0.15 with pip:

$ pip install markupsafe==0.15

I tried to install 0.16 but it produced the mentioned errors, the unicode literals seem to be introduced in 0.16,
