### ISSUE TITLE
Python.h no such file or directory

### ISSUE THREAD

**Issue by sw-dev-code** [pallets/markupsafe#312]
I'm using the Ubuntu 20.04.4 OS with manually installed `Python 3.7.3`. When I try to use `markupsafe` the following error occurs. 

I try to install the `python3-dev` but that didn't help. I can find a Python.h file at location: `/usr/local/include/python3.7m/Python.h`

tools.utils.ToolException: ./venv/lib/python3.7/site-packages/markupsafe/_speedups.c:1:10: fatal error: Python.h: No such file or directory
    1 | #include <Python.h>

**Comment by davidism** [comment]
Sorry, I can't help you with this, this is not an issue with MarkupSafe.
