### ISSUE TITLE
Wheel for Python 3.11

### ISSUE THREAD

**Issue by rikardn** [pallets/markupsafe#327]
Python 3.11 will be released today. Do you have any plans for wheels for Python 3.11 on PyPI?

**Comment by davidism** [comment]
Yes, like all previous Python releases, I plan to add wheels for 3.11 for the latest MarkupSafe release when I have time.

**Comment by rikardn** [comment]
Thanks. Much appreciated!

**Comment by ssbarnea** [comment]
Can we please do release this with py311 wheel?

**Comment by ssbarnea** [comment]
Apparently santa is busy this year...

**Comment by davidism** [comment]
2.1.2 has been released, with 3.11 wheels and SLSA provenance. #346 #347

https://github.com/pallets/markupsafe/releases/tag/2.1.2
