### ISSUE TITLE
release 2.1.2

### ISSUE THREAD

**Issue by brondsem** [pallets/markupsafe#328]
Can a 2.1.2 release be made?

The last release 2.1.1 in March had a regression, and it has been fixed but not released.  https://github.com/pallets/markupsafe/blob/main/CHANGES.rst

This is particularly troublesome since [Werkzeug depends on MarkupSafe>=2.1.1](https://github.com/pallets/werkzeug/blob/main/setup.py) so it pulls in a version of Markupsafe with a regression.

Thanks

**Comment by aluuu** [comment]
Hello @davidism,

Is it feasible to get 2.1.2 version released with the fix of the regression anytime soon or there's something you wanted to do before the release? I face the same bug #310 as Dave and it would be nice to have Markupsafe.

Thanks in advance!

**Comment by davidism** [comment]
2.1.2 has been released, with 3.11 wheels and SLSA provenance. #346 #347

https://github.com/pallets/markupsafe/releases/tag/2.1.2

---

Please note that issues like this are not helpful to us as maintainers, and I will usually close them immediately. I was on a much needed vacation, so I didn't do that when this was opened. We're already aware of the fixes that are waiting, of new Python versions, etc., bugging us about them is just stressful, not helpful.
