### ISSUE TITLE
Missing override to `format_map`

### ISSUE THREAD

**Issue by xmo-odoo** [pallets/markupsafe#370]
[`str.format_map`](https://docs.python.org/3/library/stdtypes.html?highlight=format_map#str.format_map) was added in 3.2, but it's not overridden by markupsafe, so if a user `format_map`s into a `Markup` expecting the same behaviour as `format` or `__mod__` they'll be disappointed:
```python
>>> Markup('{a}').format(a='<>')
Markup('&lt;&gt;')
>>> Markup('{a}').format_map({'a': '<>'})
'<>'
```

**Comment by davidism** [comment]
I've noticed some other `str` methods that return `str` and should be wrapped as well.

**Comment by davidism** [comment]
MarkupSafe 2.1.3 is now available on PyPI.
