### ISSUE TITLE
Python 3.12 manylinux wheels

### ISSUE THREAD

**Issue by hrnciar** [pallets/markupsafe#392]
Hello.

Could you please release CPython 3.12 manylinux wheels on PyPI?

Python 3.12.0 release candidate 1 was released two weeks ago: https://www.python.org/downloads/release/python-3120rc1/

It should be quite safe to release wheels for a release candidate. ABI for Python 3.12 should be frozen from now on, even for bugfixes. From release notes:

> There will be no ABI changes from this point forward in the 3.12 series, and the goal is that there will be as few code changes as possible.

Thank You.

**Comment by hrnciar** [comment]
I am asking this because the latest Fedora 39 beta already uses Python 3.12.0rc1. We want to allow users to do `pip install markupsafe` from day 1 hence asking in advance. Also releasing wheels now will allow other projects depending on Markupsafe to test with Python 3.12 (e.g. Jupyter Notebook). This was extensively discussed in the past between Numpy maintainers, us (Fedora maintainers) and core CPython developers, see  https://github.com/numpy/numpy/issues/19630#issuecomment-896386431

Could you please reconsider? If there is anything I can do to help (such as PR for adding new wheels), I am happy to do so.

**Comment by davidism** [comment]
Python 3.12 wheels for MarkupSafe 2.1.3 are available on PyPI.
