### ISSUE TITLE
Some sort of mapping function

### ISSUE THREAD

**Issue by xmo-odoo** [pallets/markupsafe#429]
One of the biggest issues of markupsafe is that most of the world is not markupsafe-aware, so when performing text transformations through markupsafe-unaware (but safe) APIs. In my experience, regex and markdown are common issues.

They generally require type-checking the input, applying the transformation, then re-wrapping if necessary, commonly transforming a simple expression into several statements (or a more complicated conditional expression).

Would be nice if markupsafe provided a `markupsafe.map` utility which did that internally, applying a user-supplied transformation function then rewrapping the input to match the output.

**Comment by davidism** [comment]
This sounds outside the scope of MarkupSafe. I'm not clear what this would be compared to `Markup(markdown.render(value))`.
