### ISSUE TITLE
TypeError: object.__new__(Markup) is not safe, use unicode.__new__() in specific cases

### ISSUE THREAD

**Issue by voidus** [pallets/markupsafe#50]
Hi,

I am currently struggling with a pretty weird bug. It only appears in specific situations. 

When I run a test via [sniffer](https://github.com/jeffh/sniffer) on a sadly not-that-small example, I get the following error every time except the first run. (Re-run can be triggered by touching e.g the application.py file)
```TypeError: object.__new__(Markup) is not safe, use unicode.__new__()```

I filed an issue over at flask's, but I was hoping you guys could take a look, too.
It's at https://github.com/mitsuhiko/flask/issues/1700 and I'd suggest discussing it over there for now.

**Comment by davidism** [comment]
closing, see explanation on linked issue
