### ISSUE TITLE
escape doesn't appear to handle unicode quotes correctly

### ISSUE THREAD

**Issue by nefarioustim** [pallets/markupsafe#58]
I've recently had some issues in Jinja2 with strings containing unicode quotes. Having tested directly in markupsafe, I can see the same issue:

```
>>> escape(u"Denny’s Uniforms")
Markup(u'Denny\u2019s Uniforms')
>>> escape(u"Denny‘s “Uniforms”")
Markup(u'Denny\u2018s \u201cUniforms\u201d')
>>> escape(u"Try something else—an em-dash")
Markup(u'Try something else\u2014an em-dash')
```

I was expecting this:

```
>>> escape(u"Denny’s Uniforms")
Markup(u'Denny&rsquo;s Uniforms')
>>> escape(u"Denny‘s “Uniforms”")
Markup(u'Denny&rsquo;s &ldquo;Uniforms&rdquo;')
>>> escape(u"Try something else—an em-dash")
Markup(u'Try something else&mdash;an em-dash')
```

Alternatively (potentially for better compatibility), even the numeric alternatives:

```
>>> escape(u"Denny’s Uniforms")
Markup(u'Denny&#8217;s Uniforms')
>>> escape(u"Denny‘s “Uniforms”")
Markup(u'Denny&#8217;s &#8220;Uniforms&#8221;')
>>> escape(u"Try something else—an em-dash")
Markup(u'Try something else&#8212;an em-dash')
```

In my Jinja2 template (which I'm using to generate basic XML), I'm using this to trigger the escaping:

```
<some_xml_tag>{{ supplier.name|e }}</some_xml_tag>
```

Not entirely sure if this is an issue or a misuse on my part, so any help is greatly appreciated. Thanks in advance!

**Comment by davidism** [comment]
You're confusing the `repr` output in the Python 2 console with the actual data. Python 3 improves this experience by outputting unicode. `escape`, as documented, escapes characters that have meaning in HTML. Unicode characters are completely valid.  Your Jinja code is doing the same thing as your console code.
