### ISSUE TITLE
improved docs about this project's provenance

### ISSUE THREAD

**Issue by jvanasco** [pallets/markupsafe#70]
It would be nice if the README and github config noted this is now the "official" repo for markupsafe.

It took me an absurd amount of time to realize this wasn't a fork of pocoo or Armin Ronacher's repo... but actually the same official repo under a new name.

There's still a lot of Search Engine equity on the pocoo pages (e.g http://www.pocoo.org/projects/markupsafe ) and mitsuhiko repo ( http://github.com/mitsuhiko/markupsafe ), and that all makes it seem like `pallets` is some scammy forked repo.

**Comment by davidism** [comment]
They all redirect to the same repo.

**Comment by davidism** [comment]
PyPI also points at the pallets org for the homepage.
