### ISSUE TITLE
proposal: escape backspace ascii control character

### ISSUE THREAD

**Issue by jvanasco** [pallets/markupsafe#71]
When inputting the backspace ascii control character sequence `\b`, it will remain a control character (`\x08`) when run through `escape`.  I propose escaping `\x08` to the string sequence `\b`.

The current behavior can allow for malicious users to create carefully crafted HTML strings in certain contexts. as `\x08` is a non-printing character in most GUI browsers, but will still copy to the system clipboard as part of selected text.

For example, a markupsafe-escaped string on a sample of code entered into a bugtracking application might be `import y\bose\bm\bi\bt\be\b `, which renders as `import yosemite` in HTML; if copied/pasted into a Python (or Ruby, or several other language's) interpreter - the backspace will be interpreted and the executed line will become `import os`.  

I understand this is beyond HTML as it involves the secondary usage of content generated by markupsafe -- and not the initial rendering. This may not be the most appropriate place to address this usage case, but I was surprised to find raw ASCII control characters in a "HTML" string.

**Comment by davidism** [comment]
Should we handle other problematic characters besides the backspace?

**Comment by davidism** [comment]
This seems reasonable to check for, but I'd like to hear from other @pallets/organizers. Should this be part of `escape`, or should there be a separate `escape_ascii`?

**Comment by jvanasco** [comment]
@davidism The bulk of the "lower" ASCII items are invisible and don't print (00-31).  Some of them do print though...

09 - tab
10 - line feed
11 - vertical tab
12 - form feed
13 - carriage return

The only ones I've seen that are 'dangerous'/'unsafe' are:

08 - backspace
127 - delete

Here is an example.

Run the following python:
```
lines = ("This will delete the `x` character when copy/pasted -->x%s<-- using ASCII-8" % chr(8),
	     "This will delete the `x` character when copy/pasted -->x%s<-- using ASCII-127" % chr(127),
	     )
open('test_ascii-output.txt', 'w').write("\n".join(lines))
```

If you open `test_ascii-output.txt`, some browsers/editors may show the non-printing character next to an "X.  Many won't.  Depending on what you use, viewing the file will have lines that can look like:

```
This will delete the `x` character --><--
This will delete the `x` character -->x<--
This will delete the `x` character -->x^?<--
```
Copy/pasting those lines into a terminal, however, will execute the 8/127 ascii codes, and the lines will look like this:

```
This will delete the `x` character --><--
```

Some newer browsers have been addressing this and will print the unsafe character (I've escalated this issue with a few groups).  Many don't though, and you have no idea the unsafe character is in the document or clipboard.

**Comment by davidism** [comment]
So I haven't forgotten about this, I see it every time I do work on MarkupSafe, but I've just never been able to reach a conclusion.

I agree, backspace and delete control characters can be abused. But terminals and browsers seem to be getting smarter about it.

Also, unlike the current HTML character references, there would be no way to `unescape` this, because it looks no different than an intentional `\b` literal in code. It would no longer be true that `unescape(escape(value)) == value`. The closed PR removed it when calling `striptags`, which has the same issue.

**Comment by davidism** [comment]
I read up more on code copy paste attacks, and backspace isn't nearly the only issue. Newlines can cause multi-line commands to execute, control characters like ^C might still get interpreted, Vim might see the tab or escape sequence and do something, etc. And of course there's plenty of other ways to craft seemingly innocuous commands that do something unintended.

For now, I'm going to close this issue. Markupsafe is concerned with the immediate issue of executing JavaScript in the browser. Terminals and terminal programs are in a better position to mitigate copy paste issues.
