### ISSUE TITLE
PRs failing due to AppVeyor

### ISSUE THREAD

**Issue by hugovk** [pallets/markupsafe#78]
PRs (like #75) are being marked as failed because the AppVeyor build failed.

![image](https://user-images.githubusercontent.com/1324225/31318025-136e481a-ac54-11e7-9ee0-d3fa701aaa3a.png)

The failure is:
```
Build started
git clone -q https://github.com/pallets/markupsafe.git C:\projects\markupsafe
git fetch -q origin +refs/pull/75/merge:
git checkout -qf FETCH_HEAD
Specify a project or solution file. The directory does not contain a project or solution file.
```
https://ci.appveyor.com/project/davidism/markupsafe/build/1.0.18

This is because AppVeyor has been enabled for this repo, but there's no appveyor.yml config file yet to tell it how to build and test. I see there's an open PR for this at https://github.com/pallets/markupsafe/pull/65.

In the meantime, I recommend popping over to https://ci.appveyor.com/project/pallets/markupsafe/settings and checking "Skip branches without appveyor.yml":

![image](https://user-images.githubusercontent.com/1324225/31318038-561eb87a-ac54-11e7-8871-2df255fec1e3.png)

I believe that will stop the "failure" noise on PRs which are otherwise fine. Thank you!

**Comment by davidism** [comment]
Thanks, this was actually from me experimenting on my branch, for some reason it reported the failures here. Fixed.
