### ISSUE TITLE
Fails to install on Debian 9 docker images

### ISSUE THREAD

**Issue by genodeftest** [pallets/markupsafe#84]
Steps to reproduce:
1. have a Debian 9 docker image
2. make sure that `python-pip` is installed from `apt-get`
3. run `pip install -U pip` to get a working pip version
4. run `pip install sphinx`

What happens:
During installing dependencies of sphinx, pip tries to install MarkupSafe. This step fails:
```
Collecting MarkupSafe>=0.23 (from Jinja2>=2.3->sphinx)
  Downloading MarkupSafe-1.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
    ImportError: No module named setuptools
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-CzgXau/MarkupSafe/
```

What should happen:
Install fine.

Additional info:
I think your package is missing a dependency on `setuptools` so that `pip` knows to install it before MarkupSafe.
You might also have a look at this docker log: https://travis-ci.org/exaile/exaile-testimg/builds/298234174?utm_source=github_status&utm_medium=notification

**Comment by ThiefMaster** [comment]
setuptools should always be installed. I'm tempted to call a python 
environment without setuptools broken.

**Comment by genodeftest** [comment]
setuptools is part of python.org builds, but not installed by default on Debian 9.

**Comment by davidism** [comment]
Then install it first?

**Comment by genodeftest** [comment]
I'm not clear either. I guess there is no clean solution for this.
