### ISSUE TITLE
CI always skips _speedups tests

### ISSUE THREAD

**Issue by davidism** [pallets/markupsafe#94]
Some tests are set up to run against `_native` as well as `_speedups` if it is importable. I've confirmed that they run locally, but when running on Travis and AppVeyor the `_speedups` module is always skipped.

I ran some builds with `pip -v` and `tox -vv` enabled, and the speedups are clearly being built and added to the wheel, but they must not be installed because the tests with `_speedups` are skipped.

I'm not sure where to go from here. Maybe there's a better way to debug what's getting installed by Tox? Maybe the source code is being preferred on the Python path over the virtualenv in Tox? (But I think that would affect my local tests as well.)

cc @RonnyPfannschmidt

**Comment by RonnyPfannschmidt** [comment]
happens locally on tox

**Comment by RonnyPfannschmidt** [comment]
```
[testenv:build]
commands=
	python -c 'import markupsafe._speedups'
```
fails - i suspect a tox misconfiguration or a tox issue, will investigate more in a bit

**Comment by davidism** [comment]
Hmm, you're right, it was only succeeding locally for me because I had MarkupSafe installed in editable mode in the project env, which built the speedups. Somehow the package in Tox was picking up the speedups in the project env instead of the test env.

**Comment by RonnyPfannschmidt** [comment]
ah - i figured the issue - its the `python -m pytest` implied by coverage run - this changes pythonpath in a messed up way
