### ISSUE TITLE
Deprecation warning

### ISSUE THREAD

**Issue by patreeceeo** [pallets/markupsafe#99]
I get this warning when running py.test on a freshly generated cookiecutter project:

```
.../python3.7/site-packages/markupsafe/__init__.py:13: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  from collections import Mapping
```

## Steps to reproduce:

1. generate project & answer prompts

```
mkdir project && cd project &&
cookiecutter gh:Pylons/pyramid-cookiecutter-starter
```

2. install packages

```
cd project && python3 -m venv env && source env/bin/activate &&
pip install -e .
```

3. run py.test (assuming project was named "project" in step 1)

```
py.test project/tests.py
```

I'm somewhat new to Python so maybe I'm mistaken in thinking this is an issue. Or maybe I'm not supposed to be using Python 3 with this package? Anyway, hope this is helpful in some way.

**Comment by tirkarthi** [comment]
Fixed with #98 

Thanks

**Comment by azmeuk** [comment]
Has it been released yet?

**Comment by tirkarthi** [comment]
No, it's still only in master.

**Comment by jaraco** [comment]
Having had a release for this would have saved a commit to a project that depends on it to suppress the warning. Would love a release.
